In [1]:
import torch

In [2]:
def activation(x):
    # x= torch.tensor
    
    return 1/(1+torch.exp(-x))

In [5]:
#single layer NN
#generate some data
torch.manual_seed(7)

#generate features of 5 random normal variables
features = torch.randn((1,5))

#generate weights
weights = torch.rand_like(features)

#generate bias
bias = torch.randn((1,1))

In [32]:
#use mm or matmul
#reshape or view to change the size

z=torch.mm(features, weights.view(5,1))

In [41]:
# add bias and pass through the activation function

In [34]:
output=activation(z+bias)

In [36]:
output

tensor([[0.6140]])

In [42]:
#using .sum()
z1 = activation(features*weights.sum() + bias)

In [43]:
z1

tensor([[0.2331, 0.6663, 0.7341, 0.0413, 0.9253]])

In [44]:
#using torch.sum()
z2 = activation(torch.sum(features*weights)+ bias)

In [45]:
z2

tensor([[0.6140]])

In [46]:
#multi layer network
features = torch.randn((1,3))

In [51]:
#define the NN arch
# size of input layer
n_input = features.shape[1]

# size of hidden layers
n_hidden =2
n_output=1

# define weights
weights_h1 = torch.randn((n_input, n_hidden))
weights_h2 = torch.randn((n_hidden,n_output))

#define bias
bias1= torch.randn((1,n_hidden))
bias2 = torch.randn((1,n_output))

In [54]:
#output of first hidden layer
o1 = activation(torch.mm(features,weights_h1)+bias1)

In [55]:
o1

tensor([[0.0542, 0.7109]])

In [56]:
o2= activation(torch.mm(o1, weights_h2)+ bias2)

In [57]:
# output of NN
o2

tensor([[0.5635]])

In [58]:
# from Numpy to tensor

In [60]:
import numpy as np

In [61]:
a = np.random.rand(4,3)

In [62]:
a

array([[0.88581185, 0.80046515, 0.97238044],
       [0.89851105, 0.88880894, 0.02964887],
       [0.94002525, 0.23316694, 0.48218433],
       [0.94884077, 0.50884855, 0.3066123 ]])

In [63]:
b= torch.from_numpy(a)

In [64]:
b

tensor([[0.8858, 0.8005, 0.9724],
        [0.8985, 0.8888, 0.0296],
        [0.9400, 0.2332, 0.4822],
        [0.9488, 0.5088, 0.3066]], dtype=torch.float64)

In [65]:
b.numpy()

array([[0.88581185, 0.80046515, 0.97238044],
       [0.89851105, 0.88880894, 0.02964887],
       [0.94002525, 0.23316694, 0.48218433],
       [0.94884077, 0.50884855, 0.3066123 ]])

In [66]:
b.mul_(2)

tensor([[1.7716, 1.6009, 1.9448],
        [1.7970, 1.7776, 0.0593],
        [1.8801, 0.4663, 0.9644],
        [1.8977, 1.0177, 0.6132]], dtype=torch.float64)

In [67]:
a

array([[1.77162369, 1.6009303 , 1.94476087],
       [1.7970221 , 1.77761789, 0.05929774],
       [1.88005051, 0.46633389, 0.96436866],
       [1.89768154, 1.0176971 , 0.61322461]])

In [68]:
#numpy and tensor share the same memory location, so if values are changed in-place for one object then others will also change